version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - mongodb
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=marketing_user
      - MYSQL_PASSWORD=marketing_pass
      - MYSQL_DB=marketing_db
      - MONGODB_URI=mongodb://mongodb:27017/marketing
      - OPENAI_API_KEY=sk-xxx
      - SECRET_KEY=supersecretkey
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: marketing_db
      MYSQL_USER: marketing_user
      MYSQL_PASSWORD: marketing_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mysql_data:
  mongo_data:
